# Generated by Django 4.2.30 on 2026-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_eventinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
