# Generated by Django 4.2.30 on 2026-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_eventinquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
