# Generated by Django 4.2.30 on 2026-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menuitem_options_menuitem_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
